# Basic
title: 陶志强
subtitle: 个人站
description: 这是一个菜鸟的博客~
# 头像里面的标题
avatarTitle: tao7477
# 头像里面的描述
avatarDesc: 前端开发 / 初级
url: "https://tao7477.github.io"

# Comment
comment:
    disqus: tao7477
    

# Social
social:
    weibo: 
    github: tao7477
    # twitter: 
    mail: 2102199868@qq.com

# 百度统计 
# 使用博客模板请去掉或者更换 id 
baidu:
    id: 38cf0049b9c13bdd2906df6230c3a9d6  

# Google Analytics
# 使用博客模板请去掉或者更换 id
#  ga:
    #  id: UA-84134159-3   
    #  host: auto  





permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: 博客主页

# Navigation buttons in the front page.s
nav:
    - {title: 所有文章, description: archive, url: '/archive'}   
    - {title: 标签, description: tags, url: '/tags'}      
    - {title: 关于我, description: about, url: '/about'}      
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"
  
